sql_dateformate: yyyy-MM-dd HH:mm:ss
view_dateformate: dd-MMM-yyyy
date_EndTimeZone: Asia/Muscat
date_StartTimeZone: +04:00
client_dateformate: dd/MM/yyyy

logging:
  file:
    name: E:/MicroService Log/Bidproc-des/qa/common-log.log

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      default-zone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/bidproc_new?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
