date_EndTimeZone: Asia/Muscat
date_StartTimeZone: +04:00
sql_dateformate: yyyy-MM-dd HH:mm:ss

logging:
  file:
    name: E:/MicroService Log/Bidproc-des/common-log.log

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      default-zone: http://localhost:8761/eureka/
